name: Accion personalizada
description: "adas"
author: "Yo"
inputs:  
  num-octocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
outputs:
   environment:
    description: "Environment"
    value: "${{ steps.set-env.outputs.environment }}"
  
runs:
  using: composite
  steps:
    - name: Determine Environment
      id: set-env
      shell: bash
      run: |        
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "environment=production" > $GITHUB_OUTPUT
        else
          echo "environment=staging" >> $GITHUB_OUTPUT
        fi              