name: Deploy React APp

on:
  push:
    branches:
      - main
      - staging

jobs:

  buildAndDetectEnvironment:
    uses: ./.github/workflows/BuildWF.yml
    with:
      useCache: true
  


  deploy:
    runs-on: ubuntu-latest
    needs: [buildAndDetectEnvironment]
    environment: ${{ needs.buildAndDetectEnvironment.outputs.environment }}  # Usamos el entorno calculado en detect-environment            
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.buildAndDetectEnvironment.outputs.artifact_name }}      
          path: build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build       
