name: Deploy React APP

on:

  workflow_call: 
    inputs:
      base_path: 
        description: working dir
        type: string
        default: '.'
  push: 

jobs:  
  build:
    defaults:
      run:
        working-directory: ${{inputs.base_path || '.'}}
    runs-on: ubuntu-latest    
    outputs:
      artifact_name: ${{ steps.app-info.outputs.artifact_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Progress 10%
        uses: ./.github/actions/progress-status
        with:
          total_steps: 10
          completed_steps: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Progress 20%
        uses: ./.github/actions/progress-status
        with:
          total_steps: 10
          completed_steps: 2 

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{inputs.base_path || '.'}}/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if:  ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm install      
        
      - name: Progress 40%
        uses: ./.github/actions/progress-status
        with:
          total_steps: 10
          completed_steps: 4 

      - name: obtain App Name Version for artifact
        id: app-info
        run: |
          APP_NAME=$(jq -r .name package.json)
          APP_VERSION=$(jq -r .version package.json)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "artifact_name=$APP_NAME-$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Build Project 
        run: |        
            npm run build          

      - name: Progress 60%
        uses: ./.github/actions/progress-status
        with:
          total_steps: 10
          completed_steps: 6 



      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.app-info.outputs.artifact_name }}
          path: ${{inputs.base_path || '.'}}/build/

      - name: Progress 80%
        uses: ./.github/actions/progress-status
        with:
          total_steps: 10
          completed_steps: 8      

  detect-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:  
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Determine Environment
           id: set-env
           uses: ./.github/actions/detect-environment           




  deploy:
    runs-on: ubuntu-latest
    needs: [detect-environment,build]
    environment: ${{ needs.detect-environment.outputs.environment }}  # Usamos el entorno calculado en detect-environment            
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: build/

      - name: Progress 90%
        uses: ./.github/actions/progress-status
        with:
          total_steps: 10
          completed_steps: 8        

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build      
          
      - name: Progress 100%
        uses: ./.github/actions/progress-status
        with:
          total_steps: 10
          completed_steps: 10        
